name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg

          user: Laila-M-Shawky
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6
          plugin_languages_sections: most-used

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_followup: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          plugin_isocalendar: yes
